

spring:
  application:
    ##当前的服务名称
    name: eureka
server:
  ##端口号
  port: 8000

eureka:
  instance:
    hostname: eureka
  client:
    ##检索服务
    fetch-registry: false
    ##是否将自己注册到eureka,设置为false,自己不注册到自己的服务
    register-with-eureka: false
    service-url:
      #默认的eureka服务自己，由于自己本来就是eureka,所以填写自己地址即可
      defaultZone: http://localhost:8000/eureka
  server:
    ##当eureka启动时，不能从集群节点中获取到instance注册信息，应该等多久
    wait-time-in-ms-when-sync-empty: 0
    ##自我保护机制是否开启，开启关闭都有优缺点，后面说明
    enable-self-preservation: true
    ##eureka多长时间更新一次数据
    peer-eureka-nodes-update-interval-ms: 100000